### ISSUE TITLE
index.json images are not displayed correctly

### ISSUE THREAD

**Issue by synox** [adobe/franklin-sidekick-library#63]
e.g. https://main--24life--hlxsites.hlx.page/articles.json

has images with a path like `/focus/2016/media_1086b7…at=pjpg&optimize=medium`

and the extension does not show the image preview, because the wrong host is used. The image is loaded from chrome-extension://ccfggkjabjahcjoljmgmklhpaccedipo/fitness/2016/media_180d9d498b84b24b79db58bc929764b37524c07c7.jpeg?width=1200&format=pjpg&optimize=medium 

### Expected Behaviour
Shows image

### Actual Behaviour
![Screenshot 2023-08-23 at 14 58 58](https://github.com/adobe/franklin-sidekick-library/assets/2250964/2981c8cb-df56-4709-9377-d2e29b0e86f3)

#### Steps to Reproduce
Open https://main--24life--hlxsites.hlx.page/articles.json

#### Platform and Version
Chrome on Macos

**Comment by dylandepass** [comment]
@synox Thanks for reporting the issue.

This should be logged against https://github.com/adobe/helix-sidekick-extension

Going to close here

**Comment by synox** [comment]
moved to https://github.com/adobe/helix-sidekick-extension/issues/515
